/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugThankYouRouteImport } from './routes/s.$slug.thank-you'
import { Route as ProtectedResponsesSurveyIdRouteImport } from './routes/_protected.responses.$surveyId'
import { Route as ProtectedBuilderSurveyIdRouteImport } from './routes/_protected.builder.$surveyId'
import { Route as ProtectedAnalyticsSurveyIdRouteImport } from './routes/_protected.analytics.$surveyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugThankYouRoute = SSlugThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => SSlugRoute,
} as any)
const ProtectedResponsesSurveyIdRoute =
  ProtectedResponsesSurveyIdRouteImport.update({
    id: '/responses/$surveyId',
    path: '/responses/$surveyId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBuilderSurveyIdRoute =
  ProtectedBuilderSurveyIdRouteImport.update({
    id: '/builder/$surveyId',
    path: '/builder/$surveyId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAnalyticsSurveyIdRoute =
  ProtectedAnalyticsSurveyIdRouteImport.update({
    id: '/analytics/$surveyId',
    path: '/analytics/$surveyId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/analytics/$surveyId': typeof ProtectedAnalyticsSurveyIdRoute
  '/builder/$surveyId': typeof ProtectedBuilderSurveyIdRoute
  '/responses/$surveyId': typeof ProtectedResponsesSurveyIdRoute
  '/s/$slug/thank-you': typeof SSlugThankYouRoute
  '/s/$slug/': typeof SSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/analytics/$surveyId': typeof ProtectedAnalyticsSurveyIdRoute
  '/builder/$surveyId': typeof ProtectedBuilderSurveyIdRoute
  '/responses/$surveyId': typeof ProtectedResponsesSurveyIdRoute
  '/s/$slug/thank-you': typeof SSlugThankYouRoute
  '/s/$slug': typeof SSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/_protected/analytics/$surveyId': typeof ProtectedAnalyticsSurveyIdRoute
  '/_protected/builder/$surveyId': typeof ProtectedBuilderSurveyIdRoute
  '/_protected/responses/$surveyId': typeof ProtectedResponsesSurveyIdRoute
  '/s/$slug/thank-you': typeof SSlugThankYouRoute
  '/s/$slug/': typeof SSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/s/$slug'
    | '/analytics/$surveyId'
    | '/builder/$surveyId'
    | '/responses/$surveyId'
    | '/s/$slug/thank-you'
    | '/s/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/analytics/$surveyId'
    | '/builder/$surveyId'
    | '/responses/$surveyId'
    | '/s/$slug/thank-you'
    | '/s/$slug'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/dashboard'
    | '/s/$slug'
    | '/_protected/analytics/$surveyId'
    | '/_protected/builder/$surveyId'
    | '/_protected/responses/$surveyId'
    | '/s/$slug/thank-you'
    | '/s/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/thank-you': {
      id: '/s/$slug/thank-you'
      path: '/thank-you'
      fullPath: '/s/$slug/thank-you'
      preLoaderRoute: typeof SSlugThankYouRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_protected/responses/$surveyId': {
      id: '/_protected/responses/$surveyId'
      path: '/responses/$surveyId'
      fullPath: '/responses/$surveyId'
      preLoaderRoute: typeof ProtectedResponsesSurveyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/builder/$surveyId': {
      id: '/_protected/builder/$surveyId'
      path: '/builder/$surveyId'
      fullPath: '/builder/$surveyId'
      preLoaderRoute: typeof ProtectedBuilderSurveyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics/$surveyId': {
      id: '/_protected/analytics/$surveyId'
      path: '/analytics/$surveyId'
      fullPath: '/analytics/$surveyId'
      preLoaderRoute: typeof ProtectedAnalyticsSurveyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedAnalyticsSurveyIdRoute: typeof ProtectedAnalyticsSurveyIdRoute
  ProtectedBuilderSurveyIdRoute: typeof ProtectedBuilderSurveyIdRoute
  ProtectedResponsesSurveyIdRoute: typeof ProtectedResponsesSurveyIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedAnalyticsSurveyIdRoute: ProtectedAnalyticsSurveyIdRoute,
  ProtectedBuilderSurveyIdRoute: ProtectedBuilderSurveyIdRoute,
  ProtectedResponsesSurveyIdRoute: ProtectedResponsesSurveyIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface SSlugRouteChildren {
  SSlugThankYouRoute: typeof SSlugThankYouRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugThankYouRoute: SSlugThankYouRoute,
  SSlugIndexRoute: SSlugIndexRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
